# creating table

In [1]:
import pandas as pd
import re

# -------------------------------
# 1. Example: your clinical dataframe (adni_clinical)
# -------------------------------
# Assuming it's already loaded and has columns:
# ["PTID", "EXAMDATE", "DIAGNOSIS", "DXAD", ...]
# Convert EXAMDATE to datetime to make matching easier
adni_clinical = pd.read_csv("MPR-R,_GradWarp,_B1,_N3,_Scaled_DXSUM_14Sep2025.csv")

adni_clinical["EXAMDATE"] = pd.to_datetime(adni_clinical["EXAMDATE"], errors="coerce")

# -------------------------------
# 2. Example: dataframe of your images
# -------------------------------
# Suppose you have a dataframe with filenames
image_df = pd.read_csv("ID_PATH_IMGNAME_CLASS_DF.csv")

In [52]:

# -------------------------------
# 3. Extract PTID and EXAMDATE from filenames
# -------------------------------
def parse_filename(fname):
    # Extract PTID (e.g., 002_S_0413)
    ptid_match = re.search(r"(\d{3}_S_\d{4})", fname)
    ptid = ptid_match.group(1) if ptid_match else None

    # Extract date (first 8 digits in that long number after 'Br_')
    date_match = re.search(r"Br_(\d{8})", fname)
    examdate = pd.to_datetime(date_match.group(1), format="%Y%m%d") if date_match else None

    return pd.Series([ptid, examdate])

image_df[["PTID", "EXAMDATE"]] = image_df["img_name"].apply(parse_filename)

# -------------------------------
# 4. Merge with clinical dataframe
# -------------------------------
merged = pd.merge(
    image_df,
    adni_clinical[["PTID", "EXAMDATE", "DIAGNOSIS", "DXNORM", "DXMCI", "DXAD"]],
    on=["PTID"], #, "EXAMDATE"],
    how="left"   # keep all images, even if diagnosis missing
)

# -------------------------------
# 5. Inspect results
# -------------------------------
merged.head(20)

,PTID,alzheimer_or_not,img_name,path,IMGID,EXAMDATE_x,SERIES_ID,EXAMDATE_y,DIAGNOSIS,DXNORM,DXMCI,DXAD
0,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2005-12-14,1.0,1.0,-4.0,-4.0
1,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2006-06-19,1.0,1.0,-4.0,-4.0
2,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2006-11-29,1.0,1.0,-4.0,-4.0
3,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2007-12-10,1.0,1.0,-4.0,-4.0
4,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2008-12-02,1.0,1.0,-4.0,-4.0
5,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2010-01-20,1.0,1.0,-4.0,-4.0
6,007_S_0068,0.0,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2011-01-17,1.0,NaN,NaN,NaN
7,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2006-11-08,2.0,-4.0,1.0,-4.0
8,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2007-06-11,2.0,-4.0,1.0,-4.0
9,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2007-11-16,2.0,-4.0,1.0,-4.0
10,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2008-05-09,2.0,-4.0,1.0,-4.0
11,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2008-11-21,2.0,-4.0,1.0,-4.0
12,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2009-11-18,2.0,-4.0,1.0,-4.0
13,036_S_0945,0.0,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2010-12-10,3.0,NaN,NaN,NaN
14,126_S_0865,0.0,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2006-11-21,2.0,-4.0,1.0,-4.0
15,126_S_0865,0.0,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2007-05-28,2.0,-4.0,1.0,-4.0
16,126_S_0865,0.0,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2007-11-08,2.0,-4.0,1.0,-4.0
17,126_S_0865,0.0,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2008-05-28,2.0,-4.0,1.0,-4.0
18,126_S_0865,0.0,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2008-11-18,2.0,-4.0,1.0,-4.0
19,126_S_0865,0.0,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2009-11-19,3.0,-4.0,-4.0,1.0

In [62]:
merged.drop(columns=['alzheimer_or_not'], inplace=True)

In [54]:
merged.head(20)

,PTID,img_name,path,IMGID,EXAMDATE_x,SERIES_ID,EXAMDATE_y,DIAGNOSIS,DXNORM,DXMCI,DXAD
0,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2005-12-14,1.0,1.0,-4.0,-4.0
1,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2006-06-19,1.0,1.0,-4.0,-4.0
2,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2006-11-29,1.0,1.0,-4.0,-4.0
3,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2007-12-10,1.0,1.0,-4.0,-4.0
4,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2008-12-02,1.0,1.0,-4.0,-4.0
5,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2010-01-20,1.0,1.0,-4.0,-4.0
6,007_S_0068,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,176204,2010-06-01,78802,2011-01-17,1.0,NaN,NaN,NaN
7,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2006-11-08,2.0,-4.0,1.0,-4.0
8,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2007-06-11,2.0,-4.0,1.0,-4.0
9,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2007-11-16,2.0,-4.0,1.0,-4.0
10,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2008-05-09,2.0,-4.0,1.0,-4.0
11,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2008-11-21,2.0,-4.0,1.0,-4.0
12,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2009-11-18,2.0,-4.0,1.0,-4.0
13,036_S_0945,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,217793,2011-02-16,97012,2010-12-10,3.0,NaN,NaN,NaN
14,126_S_0865,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2006-11-21,2.0,-4.0,1.0,-4.0
15,126_S_0865,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2007-05-28,2.0,-4.0,1.0,-4.0
16,126_S_0865,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2007-11-08,2.0,-4.0,1.0,-4.0
17,126_S_0865,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2008-05-28,2.0,-4.0,1.0,-4.0
18,126_S_0865,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2008-11-18,2.0,-4.0,1.0,-4.0
19,126_S_0865,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,39026,2007-02-09,22295,2009-11-19,3.0,-4.0,-4.0,1.0

In [55]:
merged['DIAGNOSIS'].value_counts()

DIAGNOSIS
2.0    2115
1.0    1777
3.0    1507
Name: count, dtype: int64

In [56]:
merged['PTID'].nunique()

456

In [57]:
merged['DIAGNOSIS'].isna().sum()

np.int64(3)

In [61]:
# Ensure datetime
image_df["EXAMDATE"] = pd.to_datetime(image_df["EXAMDATE"])
adni_clinical["EXAMDATE"] = pd.to_datetime(adni_clinical["EXAMDATE"])

# Sort both DataFrames by PTID and EXAMDATE (mandatory for merge_asof)
image_df = image_df.sort_values(["PTID", "EXAMDATE"]).reset_index(drop=True)
adni_clinical = adni_clinical.sort_values(["PTID", "EXAMDATE"]).reset_index(drop=True)

# Keep only columns of interest from clinical
clinical_keep = adni_clinical[["PTID", "EXAMDATE", "DIAGNOSIS", "DXNORM", "DXMCI", "DXAD"]]

# Group by subject and merge_asof within each PTID
merged = (
    pd.concat([
        pd.merge_asof(
            grp,
            clinical_keep[clinical_keep["PTID"] == pid],
            on="EXAMDATE",
            direction="backward"
        )
        for pid, grp in image_df.groupby("PTID")
    ])
    .reset_index(drop=True)
)

merged.head(10)

,PTID_x,alzheimer_or_not,img_name,path,IMGID,EXAMDATE,SERIES_ID,PTID_y,DIAGNOSIS,DXNORM,DXMCI,DXAD
0,002_S_0413,0.0,ADNI_002_S_0413_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0413_M...,45121,2007-03-19,13894,002_S_0413,1.0,1.0,-4.0,-4.0
1,002_S_0685,0.0,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_M...,40687,2007-02-17,16308,002_S_0685,1.0,1.0,-4.0,-4.0
2,002_S_0685,0.0,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_M...,120998,2008-10-15,55756,002_S_0685,1.0,1.0,-4.0,-4.0
3,002_S_0816,1.0,ADNI_002_S_0816_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0816_M...,60469,2007-07-17,29613,002_S_0816,3.0,-4.0,-4.0,1.0
4,002_S_0938,1.0,ADNI_002_S_0938_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0938_M...,60043,2007-07-13,29621,002_S_0938,3.0,-4.0,-4.0,1.0
5,002_S_0938,1.0,ADNI_002_S_0938_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0938_M...,81316,2007-11-10,41835,002_S_0938,3.0,-4.0,-4.0,1.0
6,002_S_0954,0.0,ADNI_002_S_0954_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0954_M...,40744,2007-02-17,19979,002_S_0954,2.0,-4.0,1.0,-4.0
7,002_S_0954,0.0,ADNI_002_S_0954_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0954_M...,86638,2008-01-07,41499,002_S_0954,3.0,-4.0,-4.0,1.0
8,002_S_1070,0.0,ADNI_002_S_1070_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_1070_M...,40835,2007-02-17,23119,002_S_1070,2.0,-4.0,1.0,-4.0
9,002_S_1070,1.0,ADNI_002_S_1070_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_1070_M...,121076,2008-10-15,55655,002_S_1070,3.0,-4.0,-4.0,1.0

In [63]:
merged['DIAGNOSIS'].value_counts()

DIAGNOSIS
2.0    296
1.0    242
3.0    218
Name: count, dtype: int64

In [64]:
merged.columns

Index(['PTID_x', 'img_name', 'path', 'IMGID', 'EXAMDATE', 'SERIES_ID',
       'PTID_y', 'DIAGNOSIS', 'DXNORM', 'DXMCI', 'DXAD'],
      dtype='object')

In [66]:
merged[merged['PTID_x'] != merged['PTID_y']]

Empty DataFrame
Columns: [PTID_x, img_name, path, IMGID, EXAMDATE, SERIES_ID, PTID_y, DIAGNOSIS, DXNORM, DXMCI, DXAD]
Index: []

In [68]:
merged.drop(columns=['PTID_y'],inplace=True)

In [71]:
merged.rename({"PTID_x":"PTID"}, axis=1)

,PTID,img_name,path,IMGID,EXAMDATE,SERIES_ID,DIAGNOSIS,DXNORM,DXMCI,DXAD
0,002_S_0413,ADNI_002_S_0413_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0413_M...,45121,2007-03-19,13894,1.0,1.0,-4.0,-4.0
1,002_S_0685,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_M...,40687,2007-02-17,16308,1.0,1.0,-4.0,-4.0
2,002_S_0685,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_M...,120998,2008-10-15,55756,1.0,1.0,-4.0,-4.0
3,002_S_0816,ADNI_002_S_0816_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0816_M...,60469,2007-07-17,29613,3.0,-4.0,-4.0,1.0
4,002_S_0938,ADNI_002_S_0938_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0938_M...,60043,2007-07-13,29621,3.0,-4.0,-4.0,1.0
...,...,...,...,...,...,...,...,...,...,...
751,941_S_1197,ADNI_941_S_1197_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1197_M...,79119,2007-10-28,38741,1.0,1.0,-4.0,-4.0
752,941_S_1202,ADNI_941_S_1202_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1202_M...,63874,2007-08-01,25680,1.0,1.0,-4.0,-4.0
753,941_S_1203,ADNI_941_S_1203_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1203_M...,204856,2010-11-11,83453,2.0,NaN,NaN,NaN
754,941_S_1311,ADNI_941_S_1311_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1311_M...,97340,2008-03-13,40710,2.0,-4.0,1.0,-4.0
755,941_S_1311,ADNI_941_S_1311_MR_MPR-R__GradWarp__B1_Correct...,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1311_M...,123816,2008-10-26,56646,3.0,-4.0,-4.0,1.0

In [ ]:
# merged.to_csv("DIAGNOSES_ID_IMGNAME_PATH.csv")

# checking

In [4]:
import pandas as pd
df = pd.read_csv("DIAGNOSES_ID_IMGNAME_PATH.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PTID_x     756 non-null    object
 1   img_name   756 non-null    object
 2   path       756 non-null    object
 3   IMGID      756 non-null    int64
 4   EXAMDATE   756 non-null    object
 5   SERIES_ID  756 non-null    int64
 6   DIAGNOSIS  756 non-null    float64
 7   DXNORM     747 non-null    float64
 8   DXMCI      747 non-null    float64
 9   DXAD       747 non-null    float64
dtypes: float64(4), int64(2), object(4)
memory usage: 59.2+ KB