In [47]:
import pandas as pd

manifest = pd.read_csv("MRI_MANIFEST_CLEANED.csv")
diagnosis = pd.read_csv("All_Subjects_DXSUM_14Aug2025.csv")
diagnosis.rename(columns={"PTID":"subject_id"}, inplace=True)
subject_ids = pd.read_csv("subjects_with_paths.csv", header=None)
subject_ids.columns = ["path", "subject_id", "to_txt"]

In [48]:
merged_df = manifest.merge(diagnosis[['subject_id', 'DIAGNOSIS', 'DXAD']], on='subject_id', how='left')

In [49]:
present_ids = []

for sid in merged_df['subject_id'].unique():
    if subject_ids['subject_id'].str.startswith(sid).any():
        present_ids.append(sid)

len(present_ids)

456

In [50]:
merged_df['subject_id'].nunique(), len(present_ids)

(658, 456)

In [51]:
print(present_ids)

['003_S_1122', '114_S_0416', '073_S_0089', '003_S_0908', '007_S_1222', '041_S_0679', '011_S_0021', '126_S_0605', '141_S_0767', '057_S_0934', '002_S_1280', '127_S_1427', '002_S_0413', '002_S_1155', '022_S_0004', '011_S_0005', '022_S_0007', '011_S_0008', '011_S_0016', '067_S_0019', '011_S_0022', '023_S_0030', '023_S_0031', '035_S_0033', '099_S_0040', '007_S_0041', '023_S_0042', '022_S_0044', '011_S_0023', '035_S_0048', '099_S_0051', '011_S_0053', '067_S_0056', '018_S_0055', '067_S_0059', '023_S_0058', '099_S_0060', '023_S_0061', '022_S_0066', '007_S_0068', '023_S_0078', '067_S_0076', '023_S_0083', '067_S_0077', '023_S_0084', '027_S_0074', '023_S_0093', '099_S_0090', '022_S_0096', '007_S_0101', '020_S_0097', '023_S_0081', '130_S_0102', '099_S_0111', '127_S_0112', '023_S_0126', '022_S_0130', '027_S_0116', '023_S_0139', '131_S_0123', '007_S_0070', '098_S_0149', '007_S_0128', '067_S_0110', '098_S_0160', '027_S_0118', '128_S_0138', '035_S_0156', '128_S_0135', '128_S_0167', '098_S_0171', '011_S_0168', '032_S_0187', '128_S_0188', '114_S_0166', '114_S_0173', '014_S_0169', '136_S_0107', '128_S_0205', '136_S_0186', '023_S_0217', '128_S_0225', '005_S_0222', '128_S_0227', '128_S_0229', '130_S_0232', '128_S_0230', '027_S_0179', '013_S_0240', '005_S_0223', '018_S_0155', '007_S_0249', '128_S_0245', '128_S_0258', '098_S_0269', '011_S_0241', '136_S_0184', '128_S_0272', '130_S_0285', '041_S_0282', '027_S_0256', '127_S_0259', '035_S_0292', '099_S_0291', '007_S_0293', '136_S_0195', '130_S_0289', '127_S_0260', '041_S_0314', '131_S_0319', '082_S_0304', '067_S_0290', '013_S_0325', '023_S_0331', '098_S_0288', '014_S_0328', '067_S_0336', '005_S_0324', '011_S_0362', '099_S_0352', '016_S_0354', '035_S_0341', '082_S_0363', '014_S_0356', '023_S_0376', '018_S_0369', '007_S_0344', '131_S_0384', '027_S_0307', '114_S_0378', '023_S_0388', '099_S_0372', '136_S_0194', '127_S_0393', '041_S_0407', '131_S_0409', '127_S_0394', '136_S_0196', '027_S_0404', '027_S_0403', '053_S_0389', '094_S_0434', '067_S_0257', '133_S_0433', '005_S_0448', '073_S_0386', '131_S_0441', '131_S_0457', '114_S_0458', '032_S_0479', '099_S_0470', '041_S_0446', '136_S_0299', '027_S_0408', '130_S_0449', '133_S_0488', '057_S_0474', '133_S_0493', '027_S_0417', '006_S_0498', '136_S_0300', '037_S_0501', '126_S_0405', '057_S_0464', '014_S_0520', '014_S_0519', '128_S_0522', '133_S_0525', '053_S_0507', '094_S_0526', '027_S_0461', '099_S_0534', '128_S_0528', '062_S_0535', '016_S_0538', '099_S_0533', '022_S_0544', '128_S_0545', '033_S_0511', '006_S_0547', '041_S_0549', '005_S_0546', '014_S_0548', '099_S_0551', '033_S_0567', '031_S_0568', '033_S_0514', '005_S_0553', '013_S_0502', '033_S_0516', '035_S_0555', '005_S_0572', '036_S_0576', '014_S_0557', '013_S_0575', '073_S_0312', '073_S_0311', '116_S_0487', '037_S_0588', '036_S_0577', '014_S_0563', '131_S_0497', '041_S_0598', '130_S_0505', '023_S_0604', '114_S_0601', '014_S_0558', '116_S_0392', '005_S_0602', '128_S_0608', '067_S_0607', '005_S_0610', '023_S_0613', '023_S_0625', '127_S_0622', '133_S_0629', '133_S_0638', '136_S_0429', '053_S_0621', '057_S_0643', '082_S_0641', '098_S_0667', '073_S_0565', '052_S_0671', '032_S_0677', '006_S_0675', '126_S_0680', '136_S_0579', '006_S_0681', '131_S_0691', '002_S_0685', '094_S_0692', '036_S_0656', '016_S_0702', '094_S_0711', '141_S_0717', '126_S_0708', '033_S_0723', '141_S_0697', '062_S_0730', '127_S_0684', '126_S_0606', '033_S_0733', '133_S_0727', '033_S_0734', '033_S_0739', '006_S_0731', '036_S_0673', '033_S_0741', '021_S_0753', '016_S_0769', '116_S_0649', '128_S_0770', '057_S_0779', '036_S_0748', '130_S_0783', '062_S_0793', '036_S_0759', '116_S_0752', '141_S_0810', '036_S_0813', '067_S_0812', '002_S_0816', '027_S_0835', '029_S_0843', '029_S_0845', '141_S_0851', '141_S_0853', '057_S_0818', '023_S_0855', '127_S_0754', '029_S_0866', '141_S_0852', '057_S_0839', '029_S_0878', '011_S_0856', '099_S_0880', '011_S_0861', '023_S_0887', '136_S_0695', '033_S_0889', '020_S_0899', '029_S_0914', '023_S_0916', '133_S_0912', '141_S_0915', '033_S_0906', '073_S_0909', '033_S_0920', '022_S_0924', '098_S_0896', '033_S_0923', '094_S_0921', '082_S_0928', '023_S_0926', '002_S_0938', '126_S_0865', '128_S_0947', '003_S_0931', '002_S_0954', '022_S_0961', '023_S_0963', '052_S_0951', '109_S_0950', '057_S_0941', '127_S_0844', '114_S_0979', '057_S_0957', '127_S_0925', '141_S_0982', '053_S_0919', '109_S_0967', '099_S_0958', '024_S_0985', '013_S_0996', '016_S_0991', '041_S_1002', '033_S_1016', '057_S_1007', '141_S_1004', '036_S_0869', '036_S_0945', '016_S_1028', '109_S_1013', '051_S_1040', '128_S_1043', '133_S_1031', '013_S_1035', '023_S_1046', '053_S_1044', '099_S_1034', '029_S_1056', '127_S_1032', '024_S_1063', '031_S_1066', '136_S_0874', '109_S_1014', '029_S_1073', '051_S_1072', '036_S_1001', '082_S_1079', '052_S_0989', '003_S_1074', '141_S_1094', '128_S_1088', '016_S_1092', '033_S_1098', '011_S_1080', '023_S_1104', '114_S_1103', '094_S_1102', '094_S_1090', '016_S_1117', '114_S_1106', '141_S_1052', '016_S_1121', '082_S_1119', '035_S_0997', '126_S_1077', '002_S_1070', '027_S_1082', '023_S_1126', '006_S_1130', '051_S_1123', '099_S_1144', '051_S_1131', '141_S_1152', '133_S_0913', '127_S_1140', '036_S_1023', '133_S_1170', '109_S_1183', '067_S_1185', '062_S_1182', '094_S_1188', '036_S_1135', '109_S_1192', '023_S_1190', '013_S_1205', '130_S_1200', '031_S_1209', '029_S_1215', '007_S_1206', '029_S_1218', '941_S_1197', '027_S_1213', '005_S_1224', '941_S_1194', '037_S_1225', '941_S_1202', '027_S_1081', '941_S_1203', '126_S_1221', '094_S_1241', '013_S_1186', '116_S_1232', '141_S_1245', '023_S_1247', '057_S_1217', '141_S_1255', '067_S_1253', '094_S_1267', '082_S_1256', '023_S_1262', '016_S_1263', '027_S_1254', '057_S_1265', '057_S_1269', '128_S_1242', '116_S_1249', '052_S_1250', '002_S_1268', '136_S_1227', '013_S_1275', '033_S_1281', '011_S_1282', '036_S_1240', '033_S_1285', '062_S_1294', '062_S_1299', '027_S_1277', '020_S_1288', '051_S_1296', '033_S_1308', '094_S_1314', '029_S_1318', '016_S_1326', '007_S_1304', '131_S_1301', '109_S_1343', '130_S_1337', '022_S_1351', '051_S_1331', '051_S_1338', '941_S_1311', '126_S_1340', '041_S_1368', '052_S_1346', '052_S_1352', '029_S_1384', '027_S_1387', '027_S_1385', '073_S_1357', '024_S_1393', '131_S_1389', '057_S_1371', '057_S_1379', '127_S_1382', '022_S_1394', '128_S_1407', '128_S_1408', '041_S_1412', '094_S_1417', '127_S_1419', '041_S_1423', '041_S_1425']

In [52]:
diagnosis_df = (
    merged_df[merged_df['subject_id'].isin(present_ids)]
    .groupby('subject_id')['DXAD']
    .unique()
    .reset_index()
)

In [53]:
len(diagnosis_df)

456

In [54]:
# Make a copy so we don't mess up original
subject_ids = subject_ids.copy()
subject_ids['alzheimer_or_not'] = None

# Count occurrences as we go
occurrence_counter = {}

for _, row in merged_df.iterrows():
    sid = row['subject_id']
    dx = row['DXAD']
    
    # How many times we've seen this subject so far
    occurrence_counter[sid] = occurrence_counter.get(sid, 0) + 1
    occ = occurrence_counter[sid]
    
    # Build the matching ID for subject_ids
    if occ == 1:
        target_id = sid
    else:
        target_id = f"{sid}_{occ}"
    
    # If that target exists in subject_ids, assign the diagnosis
    mask = subject_ids['subject_id'] == target_id
    if mask.any():
        subject_ids.loc[mask, 'alzheimer_or_not'] = dx

In [55]:
subject_ids['alzheimer_or_not'].value_counts()

alzheimer_or_not
-4.0    616
 1.0    140
Name: count, dtype: int64

In [61]:
subject_ids.loc[subject_ids['alzheimer_or_not'] == -4, 'alzheimer_or_not'] = 0

In [62]:
subject_ids['alzheimer_or_not'].value_counts()

alzheimer_or_not
0      616
1.0    140
Name: count, dtype: int64

In [63]:
subject_ids.to_csv("subjects_with_alzheimers_labels.csv", index=False)

In [64]:
subject_ids[subject_ids['subject_id'] != 0].value_counts()

path                                                                                                                        subject_id    to_txt                                                                                                                                                                                     alzheimer_or_not
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1311_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081026142433381_S56646_I123816.nii  941_S_1311_2  941_S_1311_2=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_941_S_1311_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081026142433381_S56646_I123816.nii  0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0413_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070319120107557_S13894_I45121.nii   002_S_0413    002_S_0413=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0413_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070319120107557_S13894_I45121.nii     0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070217000504186_S16308_I40687.nii   002_S_0685_2  002_S_0685_2=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070217000504186_S16308_I40687.nii   0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081015130623197_S55756_I120998.nii  002_S_0685    002_S_0685=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081015130623197_S55756_I120998.nii    0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0816_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070717185729601_S29613_I60469.nii   002_S_0816    002_S_0816=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0816_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070717185729601_S29613_I60469.nii     1.0                 1
                                                                                                                                                                                                                                                                                                                                                        ..
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0222_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070805124750595_S29894_I64768.nii   005_S_0222    005_S_0222=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0222_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070805124750595_S29894_I64768.nii     0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0223_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080408093425050_S47239_I101344.nii  005_S_0223    005_S_0223=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0223_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080408093425050_S47239_I101344.nii    0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061212171807772_S12599_I32892.nii   005_S_0324    005_S_0324=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061212171807772_S12599_I32892.nii     0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071027121153965_S41672_I78695.nii   005_S_0324_4  005_S_0324_4=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071027121153965_S41672_I78695.nii   0.0                 1
MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080430143333279_S49114_I104356.nii  005_S_0324_2  005_S_0324_2=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080430143333279_S49114_I104356.nii  0.0                 1
Name: count, Length: 756, dtype: int64

In [81]:
# Filter merged_df to only present IDs
filtered_df = merged_df[merged_df['subject_id'].isin(present_ids)]

# Identify rows (assuming PTGENDER: 1 = male, 2 = female)
male_rows_ad = filtered_df[(filtered_df['PTGENDER'] == 1) & (filtered_df['DXAD'] == 1)]
female_rows_ad = filtered_df[(filtered_df['PTGENDER'] == 2) & (filtered_df['DXAD'] == 1)]
male_rows_no_ad = filtered_df[(filtered_df['PTGENDER'] == 1) & (filtered_df['DXAD'] != 1)]
female_rows_no_ad = filtered_df[(filtered_df['PTGENDER'] == 2) & (filtered_df['DXAD'] != 1)]

# Randomly select rows
yes_AD_man = male_rows_ad.sample(n=5, random_state=42).index
no_AD_man = male_rows_no_ad.sample(n=5, random_state=42).index
yes_AD_woman = female_rows_ad.sample(n=5, random_state=42).index
no_AD_woman = female_rows_no_ad.sample(n=5, random_state=42).index

# Combine all sampled rows into one DataFrame
sampled_df = pd.concat([
    male_rows_ad.loc[yes_AD_man],
    male_rows_no_ad.loc[no_AD_man],
    female_rows_ad.loc[yes_AD_woman],
    female_rows_no_ad.loc[no_AD_woman]
])

# Reset the index
sampled_df = sampled_df.reset_index(drop=True)

In [82]:
male_rows_ad.loc[yes_AD_man]["subject_id"].unique()

array(['023_S_0388', '022_S_1394', '016_S_1326', '114_S_0979',
       '036_S_1001'], dtype=object)

In [83]:
female_rows_ad.loc[yes_AD_woman]["subject_id"].unique()

array(['023_S_1247', '067_S_1253', '036_S_0869', '051_S_1331',
       '057_S_0474'], dtype=object)

In [84]:
male_rows_no_ad.loc[no_AD_man]["subject_id"].unique()

array(['052_S_1352', '032_S_0677', '022_S_0096', '128_S_1408'],
      dtype=object)

In [85]:
female_rows_no_ad.loc[no_AD_woman]["subject_id"].unique()

array(['141_S_0767', '053_S_0389', '003_S_1122', '131_S_0441',
       '023_S_0331'], dtype=object)

In [86]:
import os
import shutil
import pandas as pd

# Example: your dataframe
# df = pd.read_csv("subject_ids_with_dx.csv")  # must have a column "subject_id"
subject_ids = sampled_df["subject_id"].tolist()

# Paths
source_root = "/home/e.yavarova/alzheimers_research_lala_emiliya/FASTSURFER_MASKS"   # folder where all subject subfolders live
target_root = "/home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects"  # where to copy

os.makedirs(target_root, exist_ok=True)

for sid in subject_ids:
    src_subject = os.path.join(source_root, sid)        # e.g. /source/127_S_0844
    src_mri = os.path.join(src_subject, "mri")          # e.g. /source/127_S_0844/mri
    dst_mri = os.path.join(target_root, sid, "mri")     # e.g. /selected_subjects/127_S_0844/mri

    if os.path.exists(src_mri):
        print(f"Copying MRI files for {sid} -> {dst_mri}")
        os.makedirs(os.path.dirname(dst_mri), exist_ok=True)
        shutil.copytree(src_mri, dst_mri, dirs_exist_ok=True)
    else:
        print(f"⚠️ MRI folder not found for {sid}: {src_mri}")

Copying MRI files for 023_S_0388 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/023_S_0388/mri
Copying MRI files for 022_S_1394 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/022_S_1394/mri
Copying MRI files for 016_S_1326 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/016_S_1326/mri
Copying MRI files for 114_S_0979 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/114_S_0979/mri
Copying MRI files for 036_S_1001 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/036_S_1001/mri
Copying MRI files for 052_S_1352 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/052_S_1352/mri
Copying MRI files for 032_S_0677 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/032_S_0677/mri
Copying MRI files for 022_S_0096 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/022_S_0096/mri
Copying MRI files for 128_S_1408 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/128_S_1408/mri
Copying MRI files for 022_S_0096 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/022_S_0096/mri
Copying MRI files for 023_S_1247 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/023_S_1247/mri
Copying MRI files for 067_S_1253 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/067_S_1253/mri
Copying MRI files for 036_S_0869 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/036_S_0869/mri
Copying MRI files for 051_S_1331 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/051_S_1331/mri
Copying MRI files for 057_S_0474 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/057_S_0474/mri
Copying MRI files for 141_S_0767 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/141_S_0767/mri
Copying MRI files for 053_S_0389 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/053_S_0389/mri
Copying MRI files for 003_S_1122 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/003_S_1122/mri
Copying MRI files for 131_S_0441 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/131_S_0441/mri
Copying MRI files for 023_S_0331 -> /home/e.yavarova/alzheimers_research_lala_emiliya/selected_subjects/023_S_0331/mri

In [87]:
sampled_df.head(20)

,Unnamed: 0,subject_id,visit,PTGENDER,ARM,IHSYMPTOM,MHPSYCH,MH2NEURL,CENROLL,DIAGNOSIS,DXAD
0,9824,023_S_0388,sc,1.0,8.0,NaN,1.0,0.0,1.0,3.0,1.0
1,15762,022_S_1394,m48,1.0,5.0,NaN,1.0,0.0,1.0,3.0,1.0
2,15409,016_S_1326,m06,1.0,8.0,NaN,NaN,NaN,NaN,3.0,1.0
3,13244,114_S_0979,m12,1.0,6.0,NaN,NaN,NaN,NaN,3.0,1.0
4,13879,036_S_1001,m18,1.0,6.0,NaN,NaN,NaN,NaN,3.0,1.0
5,15613,052_S_1352,m96,1.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN
6,11487,032_S_0677,m12,1.0,7.0,NaN,NaN,NaN,NaN,1.0,NaN
7,8024,022_S_0096,4_init,1.0,4.0,NaN,NaN,NaN,NaN,1.0,NaN
8,15829,128_S_1408,m30,1.0,5.0,NaN,NaN,NaN,NaN,2.0,-4.0
9,8041,022_S_0096,m48,1.0,4.0,NaN,NaN,NaN,NaN,1.0,NaN
10,14895,023_S_1247,bl,2.0,8.0,NaN,NaN,NaN,NaN,3.0,1.0
11,14957,067_S_1253,sc,2.0,9.0,NaN,1.0,0.0,1.0,3.0,1.0
12,13509,036_S_0869,m24,2.0,2.0,NaN,NaN,NaN,NaN,3.0,1.0
13,15515,051_S_1331,m24,2.0,8.0,NaN,NaN,NaN,NaN,3.0,1.0
14,10330,057_S_0474,m06,2.0,6.0,NaN,NaN,NaN,NaN,3.0,1.0
15,3472,141_S_0767,m30,2.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN
16,9957,053_S_0389,m06,2.0,5.0,NaN,NaN,NaN,NaN,2.0,-4.0
17,100,003_S_1122,m204,2.0,5.0,3.0,NaN,NaN,1.0,2.0,-4.0
18,10099,131_S_0441,m90,2.0,7.0,NaN,NaN,NaN,NaN,1.0,-4.0
19,9482,023_S_0331,m72,2.0,8.0,NaN,NaN,NaN,NaN,2.0,-4.0

In [89]:
sampled_df.drop(columns=["Unnamed: 0", "visit", "ARM", "IHSYMPTOM", "MHPSYCH", "MH2NEURL", "CENROLL", "DIAGNOSIS"], inplace=True)

In [96]:
sampled_df.loc[sampled_df['DXAD'] != 1, 'DXAD'] = 0
sampled_df.loc[sampled_df['PTGENDER'] != 1, 'PTGENDER'] = "female"
sampled_df.loc[sampled_df['PTGENDER'] == 1, 'PTGENDER'] = "male"

/tmp/ipykernel_3101707/3658046731.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'female' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  sampled_df.loc[sampled_df['PTGENDER'] != 1, 'PTGENDER'] = "female"

In [97]:
sampled_df.head(20)

    subject_id PTGENDER  DXAD
0   023_S_0388     male   1.0
1   022_S_1394     male   1.0
2   016_S_1326     male   1.0
3   114_S_0979     male   1.0
4   036_S_1001     male   1.0
5   052_S_1352     male   0.0
6   032_S_0677     male   0.0
7   022_S_0096     male   0.0
8   128_S_1408     male   0.0
9   022_S_0096     male   0.0
10  023_S_1247   female   1.0
11  067_S_1253   female   1.0
12  036_S_0869   female   1.0
13  051_S_1331   female   1.0
14  057_S_0474   female   1.0
15  141_S_0767   female   0.0
16  053_S_0389   female   0.0
17  003_S_1122   female   0.0
18  131_S_0441   female   0.0
19  023_S_0331   female   0.0

In [100]:
sampled_df.to_csv("20_selected_mris_fastsurfer.csv", index=False)

Collecting package metadata (current_repodata.json): failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /opt/miniconda3/pkgs/cache/9e0f62c3.json
  uid: 808209227
  gid: 808200513

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 808209227:808200513 /opt/miniconda3/pkgs/cache/9e0f62c3.json

In general, it's not advisable to use 'sudo conda'.