In [ ]:
import pandas as pd

manif = pd.read_csv("adni_data/MPR-R,_GradWarp,_B1,_N3,_Scaled_Manifest_14Aug2025.csv")
db = pd.read_csv("adni_data/All_Subjects_My_Table_11Aug2025.csv")

# Filter to matching subject_ids and make a copy
patients_diagnosis = db[db['subject_id'].isin(manif['subject_id'])].copy()

cols = ["BCSTROKE", "EXNEURO", "EXNIMAG", "EXILLNESS", "EXLAB"]

# Convert columns to numeric
patients_diagnosis[cols] = patients_diagnosis[cols].apply(pd.to_numeric, errors='coerce')

# Drop rows where any column == 1
filtered_df = patients_diagnosis[~(patients_diagnosis[cols] == 1).any(axis=1)]
len(filtered_df)

In [5]:
for col in patients_diagnosis.columns:
    print(f"\n--- {col} ---")
    print(patients_diagnosis[col].value_counts(dropna=False))

--- subject_id ---
subject_id
003_S_0908    28
126_S_0605    28
027_S_0074    27
041_S_0679    27
003_S_1122    27
              ..
141_S_0340     1
014_S_0357     1
027_S_1335     1
067_S_0020     1
067_S_0024     1
Name: count, Length: 675, dtype: int64

--- visit ---
visit
bl        658
sc        658
m06       627
m12       596
m18       567
m24       530
m30       404
m36       381
m48       221
m42       216
m72       195
m60       192
m66       168
m78       167
m54       166
m84       159
m96       120
m90        97
m108       93
AUT        63
nv         61
m120       58
m144       37
m132       32
m156       23
m168       20
m180       20
m150       17
f          17
m138       15
m162       15
4_init     15
m126       12
m186       12
m102        8
m174        8
m192        7
m198        7
m222        6
m204        5
m114        5
m216        5
m234        4
m228        3
m210        3
4_m12       2
uns1        1
4_sc        1
Name: count, dtype: int64

--- PTGENDER ---
PTGENDER
1.0    3638
2.0    3059
Name: count, dtype: int64

--- ARM ---
ARM
5.0    1675
4.0    1022
8.0     849
2.0     814
7.0     785
1.0     655
6.0     450
9.0     244
3.0     203
Name: count, dtype: int64

--- BCSTROKE ---
BCSTROKE
0.0    3396
NaN    3284
1.0      17
Name: count, dtype: int64

--- IHSYMPTOM ---
IHSYMPTOM
NaN     6623
3.0       16
18.0      12
4.0        8
9.0        7
8.0        7
2.0        6
1.0        4
12.0       4
7.0        3
17.0       3
13.0       2
19.0       1
10.0       1
Name: count, dtype: int64

--- MHPSYCH ---
MHPSYCH
NaN    5649
0.0     705
1.0     343
Name: count, dtype: int64

--- MH2NEURL ---
MH2NEURL
NaN    5649
0.0     727
1.0     321
Name: count, dtype: int64

--- EXNEURO ---
EXNEURO
NaN    6022
0.0     674
1.0       1
Name: count, dtype: int64

--- EXNIMAG ---
EXNIMAG
NaN    6024
0.0     667
1.0       6
Name: count, dtype: int64

--- EXILLNESS ---
EXILLNESS
NaN    6022
0.0     673
1.0       2
Name: count, dtype: int64

--- EXLAB ---
EXLAB
NaN    6022
0.0     671
1.0       4
Name: count, dtype: int64

--- CENROLL ---
CENROLL
NaN    5720
1.0     959
0.0      18
Name: count, dtype: int64

In [6]:
for col in filtered_df.columns:
    print(f"\n--- {col} ---")
    print(filtered_df[col].value_counts(dropna=False))

--- subject_id ---
subject_id
126_S_0605    28
003_S_0908    28
027_S_0074    27
003_S_1122    27
041_S_0679    27
              ..
094_S_0964     1
033_S_0888     1
027_S_0948     1
128_S_0805     1
027_S_1335     1
Name: count, Length: 674, dtype: int64

--- visit ---
visit
bl        658
sc        646
m06       627
m12       594
m18       567
m24       528
m30       404
m36       377
m48       219
m42       216
m72       194
m60       191
m66       168
m78       167
m54       166
m84       157
m96       120
m90        97
m108       92
AUT        63
nv         61
m120       57
m144       37
m132       32
m156       22
m168       20
m180       20
m150       17
f          16
m138       15
m162       15
4_init     15
m126       12
m186       12
m102        8
m174        8
m192        7
m198        7
m222        6
m204        5
m114        5
m216        5
m234        4
m228        3
m210        3
4_m12       2
uns1        1
4_sc        1
Name: count, dtype: int64

--- PTGENDER ---
PTGENDER
1.0    3626
2.0    3041
Name: count, dtype: int64

--- ARM ---
ARM
5.0    1670
4.0    1017
8.0     848
2.0     807
7.0     779
1.0     653
6.0     449
9.0     241
3.0     203
Name: count, dtype: int64

--- BCSTROKE ---
BCSTROKE
0.0    3396
NaN    3271
Name: count, dtype: int64

--- IHSYMPTOM ---
IHSYMPTOM
NaN     6593
3.0       16
18.0      12
4.0        8
9.0        7
8.0        7
2.0        6
1.0        4
12.0       4
7.0        3
17.0       3
13.0       2
19.0       1
10.0       1
Name: count, dtype: int64

--- MHPSYCH ---
MHPSYCH
NaN    5635
0.0     695
1.0     337
Name: count, dtype: int64

--- MH2NEURL ---
MH2NEURL
NaN    5635
0.0     717
1.0     315
Name: count, dtype: int64

--- EXNEURO ---
EXNEURO
NaN    6005
0.0     662
Name: count, dtype: int64

--- EXNIMAG ---
EXNIMAG
NaN    6007
0.0     660
Name: count, dtype: int64

--- EXILLNESS ---
EXILLNESS
NaN    6005
0.0     662
Name: count, dtype: int64

--- EXLAB ---
EXLAB
NaN    6005
0.0     662
Name: count, dtype: int64

--- CENROLL ---
CENROLL
NaN    5704
1.0     946
0.0      17
Name: count, dtype: int64

In [7]:
patients_diagnosis['PTGENDER'].value_counts()

PTGENDER
1.0    3638
2.0    3059
Name: count, dtype: int64

In [8]:
patients_diagnosis['subject_id'].nunique()

675

In [9]:
# Identify male rows (assuming PTGENDER: 1 = male, 2 = female)
male_rows = filtered_df[filtered_df['PTGENDER'] == 1]

# Randomly select 600 male rows to drop
drop_males = male_rows.sample(n=600, random_state=42).index

# Drop them from the dataframe
balanced_df = filtered_df.drop(drop_males)

# Verify counts
print(balanced_df['PTGENDER'].value_counts())

PTGENDER
2.0    3041
1.0    3026
Name: count, dtype: int64

In [10]:
balanced_df = balanced_df[balanced_df["CENROLL"] != 0]

In [11]:
balanced_df['subject_id'].nunique()

658

In [12]:
balanced_df.columns

Index(['subject_id', 'visit', 'PTGENDER', 'ARM', 'BCSTROKE', 'IHSYMPTOM',
       'MHPSYCH', 'MH2NEURL', 'EXNEURO', 'EXNIMAG', 'EXILLNESS', 'EXLAB',
       'CENROLL'],
      dtype='object')

In [13]:
balanced_df.drop(columns=cols, inplace=True)

In [14]:
manif.head()

   image_id  subject_id  image_date                   image_description
0    143389  127_S_1427  2009-03-12  MPR-R; GradWarp; B1 Correction; N3
1     91130  127_S_1427  2007-08-20  MPR-R; GradWarp; B1 Correction; N3
2     99271  127_S_1427  2008-02-19  MPR-R; GradWarp; B1 Correction; N3
3    121698  127_S_1427  2008-09-02  MPR-R; GradWarp; B1 Correction; N3
4    163865  127_S_1427  2009-08-26  MPR-R; GradWarp; B1 Correction; N3

In [15]:
missing_in_balanced = manif[~manif['subject_id'].isin(balanced_df['subject_id'])]
print(missing_in_balanced.count())

image_id             23
subject_id           23
image_date           23
image_description    23
dtype: int64

In [16]:
extra_in_balanced = balanced_df[~balanced_df['subject_id'].isin(manif['subject_id'])]
print(extra_in_balanced)

Empty DataFrame
Columns: [subject_id, visit, PTGENDER, ARM, IHSYMPTOM, MHPSYCH, MH2NEURL, CENROLL]
Index: []

In [17]:
balanced_df.to_csv("MRI_MANIFEST_CLEANED.csv")

In [18]:
import pandas as pd

df = pd.read_csv("adni_data/MRI_MANIFEST_CLEANED.csv")

In [19]:
df.head()

,Unnamed: 0,subject_id,visit,PTGENDER,ARM,IHSYMPTOM,MHPSYCH,MH2NEURL,CENROLL
0,87,003_S_1122,4_init,2.0,5.0,NaN,NaN,NaN,NaN
1,88,003_S_1122,4_m12,2.0,5.0,NaN,NaN,NaN,NaN
2,89,003_S_1122,bl,2.0,5.0,NaN,NaN,NaN,NaN
3,90,003_S_1122,m06,2.0,5.0,NaN,NaN,NaN,NaN
4,91,003_S_1122,m108,2.0,5.0,NaN,NaN,NaN,NaN

In [20]:
print(",".join(df['subject_id'].unique().astype(str)))

003_S_1122,128_S_0200,114_S_0416,073_S_0089,003_S_0908,007_S_1222,041_S_0679,011_S_0021,126_S_0605,141_S_0767,057_S_0934,002_S_1280,127_S_1427,002_S_0413,002_S_1155,011_S_0002,011_S_0003,022_S_0004,011_S_0005,022_S_0007,011_S_0008,022_S_0014,011_S_0016,067_S_0019,011_S_0022,067_S_0029,023_S_0030,023_S_0031,035_S_0033,099_S_0040,007_S_0041,023_S_0042,022_S_0044,011_S_0023,018_S_0043,067_S_0038,067_S_0045,011_S_0010,035_S_0048,099_S_0051,011_S_0053,067_S_0056,018_S_0055,099_S_0054,067_S_0059,023_S_0058,099_S_0060,023_S_0061,022_S_0066,007_S_0068,023_S_0078,067_S_0076,023_S_0083,067_S_0077,023_S_0084,027_S_0074,023_S_0093,099_S_0090,022_S_0096,007_S_0101,020_S_0097,023_S_0081,130_S_0102,099_S_0111,127_S_0112,023_S_0126,041_S_0125,022_S_0130,027_S_0116,023_S_0139,131_S_0123,007_S_0070,098_S_0149,007_S_0128,018_S_0142,067_S_0110,098_S_0160,027_S_0118,128_S_0138,035_S_0156,128_S_0135,128_S_0167,027_S_0120,022_S_0129,098_S_0171,011_S_0168,032_S_0187,128_S_0188,114_S_0166,114_S_0173,067_S_0098,014_S_0169,136_S_0107,128_S_0205,067_S_0177,136_S_0186,035_S_0204,023_S_0217,005_S_0221,128_S_0216,128_S_0225,114_S_0228,022_S_0219,020_S_0213,005_S_0222,128_S_0227,128_S_0229,130_S_0232,128_S_0230,027_S_0179,013_S_0240,005_S_0223,098_S_0172,018_S_0155,011_S_0183,007_S_0249,128_S_0245,128_S_0258,067_S_0243,041_S_0262,067_S_0176,098_S_0269,011_S_0241,128_S_0266,136_S_0184,128_S_0272,130_S_0285,041_S_0282,067_S_0284,027_S_0256,127_S_0259,035_S_0292,099_S_0291,007_S_0293,136_S_0195,130_S_0289,127_S_0260,041_S_0314,131_S_0319,082_S_0304,037_S_0303,128_S_0310,021_S_0332,067_S_0290,013_S_0325,023_S_0331,098_S_0288,011_S_0326,014_S_0328,067_S_0336,005_S_0324,011_S_0362,099_S_0352,016_S_0354,035_S_0341,016_S_0359,082_S_0363,014_S_0356,023_S_0376,018_S_0369,007_S_0344,131_S_0384,114_S_0374,136_S_0086,027_S_0307,114_S_0378,023_S_0388,099_S_0372,007_S_0316,136_S_0194,127_S_0393,002_S_0295,041_S_0407,131_S_0409,127_S_0394,136_S_0196,027_S_0404,027_S_0403,114_S_0410,053_S_0389,094_S_0434,131_S_0436,067_S_0257,018_S_0406,133_S_0433,005_S_0448,073_S_0386,007_S_0414,131_S_0441,131_S_0457,114_S_0458,127_S_0431,130_S_0423,032_S_0479,018_S_0450,099_S_0470,082_S_0469,041_S_0446,136_S_0299,027_S_0408,130_S_0449,127_S_0397,133_S_0488,094_S_0489,130_S_0460,099_S_0492,006_S_0484,057_S_0474,133_S_0493,027_S_0417,006_S_0498,128_S_0500,136_S_0300,037_S_0501,027_S_0485,126_S_0405,057_S_0464,128_S_0517,014_S_0520,014_S_0519,128_S_0522,133_S_0525,053_S_0507,094_S_0526,116_S_0382,094_S_0531,027_S_0461,099_S_0534,128_S_0528,062_S_0535,016_S_0538,099_S_0533,136_S_0426,022_S_0544,128_S_0545,033_S_0511,006_S_0547,033_S_0513,022_S_0543,002_S_0559,041_S_0549,126_S_0506,005_S_0546,014_S_0548,099_S_0551,033_S_0567,031_S_0568,033_S_0514,005_S_0553,013_S_0502,033_S_0516,035_S_0555,005_S_0572,062_S_0578,036_S_0576,014_S_0557,073_S_0445,013_S_0575,073_S_0312,073_S_0311,016_S_0590,116_S_0487,037_S_0588,036_S_0577,014_S_0563,131_S_0497,041_S_0598,130_S_0505,023_S_0604,114_S_0601,013_S_0592,014_S_0558,116_S_0392,005_S_0602,128_S_0608,002_S_0619,067_S_0607,005_S_0610,023_S_0613,128_S_0611,023_S_0625,127_S_0622,133_S_0629,133_S_0638,027_S_0644,136_S_0429,082_S_0640,018_S_0633,053_S_0621,006_S_0653,057_S_0643,082_S_0641,098_S_0667,073_S_0565,052_S_0671,032_S_0677,006_S_0675,126_S_0680,136_S_0579,006_S_0681,131_S_0691,002_S_0685,062_S_0690,094_S_0692,036_S_0656,018_S_0682,007_S_0698,016_S_0702,013_S_0699,094_S_0711,141_S_0717,032_S_0718,128_S_0715,141_S_0696,126_S_0708,033_S_0723,141_S_0697,141_S_0726,062_S_0730,033_S_0724,127_S_0684,126_S_0606,002_S_0729,014_S_0658,033_S_0725,033_S_0733,133_S_0727,033_S_0734,033_S_0739,006_S_0731,036_S_0673,036_S_0672,128_S_0740,126_S_0709,033_S_0741,022_S_0750,021_S_0753,016_S_0769,116_S_0649,062_S_0768,128_S_0770,082_S_0761,109_S_0777,002_S_0782,133_S_0771,057_S_0779,036_S_0748,130_S_0783,041_S_0721,062_S_0793,036_S_0759,133_S_0792,116_S_0752,141_S_0810,036_S_0813,067_S_0812,005_S_0814,036_S_0760,141_S_0790,002_S_0816,031_S_0830,029_S_0824,067_S_0828,029_S_0836,027_S_0835,029_S_0843,029_S_0845,126_S_0784,082_S_0832,141_S_0851,141_S_0853,057_S_0818,023_S_0855,027_S_0850,127_S_0754,029_S_0866,141_S_0852,029_S_0871,057_S_0839,128_S_0863,029_S_0878,011_S_0856,099_S_0880,013_S_0860,011_S_0861,020_S_0883,109_S_0876,023_S_0887,136_S_0695,130_S_0886,033_S_0889,020_S_0899,041_S_0898,029_S_0914,023_S_0916,133_S_0912,126_S_0891,141_S_0915,033_S_0906,073_S_0909,033_S_0920,022_S_0924,098_S_0896,033_S_0923,094_S_0921,082_S_0928,033_S_0922,023_S_0926,003_S_0907,002_S_0938,005_S_0929,126_S_0865,128_S_0947,003_S_0931,136_S_0873,002_S_0954,022_S_0961,130_S_0956,023_S_0963,073_S_0518,052_S_0952,052_S_0951,109_S_0950,057_S_0941,002_S_0955,127_S_0844,114_S_0979,057_S_0957,127_S_0925,141_S_0982,130_S_0969,053_S_0919,109_S_0967,099_S_0958,024_S_0985,029_S_0999,013_S_0996,003_S_0981,016_S_0991,041_S_1002,041_S_1010,141_S_1024,033_S_1016,057_S_1007,141_S_1004,036_S_0869,036_S_0945,094_S_1015,094_S_1027,029_S_1038,016_S_1028,109_S_1013,051_S_1040,128_S_1043,133_S_1031,013_S_1035,023_S_1046,053_S_1044,003_S_1021,133_S_1055,099_S_1034,029_S_1056,127_S_1032,027_S_1045,024_S_1063,031_S_1066,003_S_1059,136_S_0874,109_S_1014,029_S_1073,051_S_1072,116_S_1083,033_S_1086,036_S_1001,003_S_1057,082_S_1079,052_S_0989,003_S_1074,141_S_1094,128_S_1088,022_S_1097,032_S_1101,016_S_1092,033_S_1098,011_S_1080,023_S_1104,114_S_1103,094_S_1102,094_S_1090,062_S_1099,014_S_1095,016_S_1117,114_S_1106,109_S_1114,033_S_1116,052_S_1054,141_S_1052,016_S_1121,114_S_1118,082_S_1119,035_S_0997,126_S_1077,073_S_0746,002_S_1070,013_S_1120,027_S_1082,023_S_1126,006_S_1130,002_S_1018,051_S_1123,141_S_1051,141_S_1137,016_S_1138,036_S_0976,099_S_1144,128_S_1148,051_S_1131,141_S_1152,133_S_0913,127_S_1140,052_S_1168,016_S_1149,032_S_1169,094_S_1164,013_S_1161,024_S_1171,109_S_1157,098_S_0884,036_S_1023,133_S_1170,109_S_1183,029_S_1184,067_S_1185,062_S_1182,094_S_1188,036_S_1135,109_S_1192,023_S_1190,013_S_1205,130_S_1200,031_S_1209,130_S_1201,029_S_1215,007_S_1206,029_S_1218,941_S_1197,126_S_1187,027_S_1213,005_S_1224,941_S_1194,037_S_1225,941_S_1202,027_S_1081,941_S_1203,126_S_1221,141_S_1231,127_S_1210,094_S_1241,013_S_1186,116_S_1232,141_S_1245,023_S_1247,057_S_1217,141_S_1255,067_S_1253,141_S_1244,094_S_1267,082_S_1256,023_S_1262,941_S_1195,016_S_1263,027_S_1254,057_S_1265,057_S_1269,128_S_1242,116_S_1249,052_S_1250,007_S_1248,003_S_1257,052_S_1251,002_S_1268,136_S_1227,033_S_1283,033_S_1279,013_S_1275,023_S_1289,033_S_1281,041_S_1260,094_S_1293,002_S_1261,130_S_1290,011_S_1282,036_S_1240,013_S_1276,033_S_1284,033_S_1285,062_S_1294,062_S_1299,027_S_1277,020_S_1288,941_S_1295,051_S_1296,023_S_1306,024_S_1307,033_S_1308,033_S_1309,094_S_1314,029_S_1318,016_S_1326,007_S_1304,131_S_1301,094_S_1330,109_S_1343,005_S_1341,130_S_1337,022_S_1351,051_S_1331,051_S_1338,941_S_1311,007_S_1339,126_S_1340,022_S_1366,041_S_1368,052_S_1346,941_S_1363,052_S_1352,141_S_1378,029_S_1384,027_S_1387,027_S_1385,073_S_1357,024_S_1393,082_S_1377,131_S_1389,057_S_1371,057_S_1373,057_S_1379,041_S_1391,127_S_1382,022_S_1394,094_S_1397,094_S_1398,024_S_1400,094_S_1402,128_S_1407,128_S_1406,041_S_1411,128_S_1408,041_S_1412,128_S_1409,094_S_1417,041_S_1418,127_S_1419,041_S_1420,041_S_1423,041_S_1425,128_S_1430,041_S_1435

In [7]:
import os
import pandas as pd

id_set = set()
dir = "adni_data/MRIs_IMAGES_FILTERED_NOMASKS"
imgs = os.listdir(dir)
len(imgs)

756

In [8]:

for fname in imgs:
    id = fname.replace("ADNI_","").split("_MR_MPR-R_")[0]
    id_set.add(id)

In [9]:
id_set

{'002_S_0413',
 '002_S_0685',
 '002_S_0816',
 '002_S_0938',
 '002_S_0954',
 '002_S_1070',
 '002_S_1155',
 '002_S_1268',
 '002_S_1280',
 '003_S_0908',
 '003_S_0931',
 '003_S_1074',
 '003_S_1122',
 '005_S_0222',
 '005_S_0223',
 '005_S_0324',
 '005_S_0448',
 '005_S_0546',
 '005_S_0553',
 '005_S_0572',
 '005_S_0602',
 '005_S_0610',
 '005_S_1224',
 '006_S_0498',
 '006_S_0547',
 '006_S_0675',
 '006_S_0681',
 '006_S_0731',
 '006_S_1130',
 '007_S_0041',
 '007_S_0068',
 '007_S_0070',
 '007_S_0101',
 '007_S_0128',
 '007_S_0249',
 '007_S_0293',
 '007_S_0344',
 '007_S_1206',
 '007_S_1222',
 '007_S_1304',
 '011_S_0005',
 '011_S_0008',
 '011_S_0016',
 '011_S_0021',
 '011_S_0022',
 '011_S_0023',
 '011_S_0053',
 '011_S_0168',
 '011_S_0241',
 '011_S_0362',
 '011_S_0856',
 '011_S_0861',
 '011_S_1080',
 '011_S_1282',
 '013_S_0240',
 '013_S_0325',
 '013_S_0502',
 '013_S_0575',
 '013_S_0996',
 '013_S_1035',
 '013_S_1186',
 '013_S_1205',
 '013_S_1275',
 '014_S_0169',
 '014_S_0328',
 '014_S_0356',
 '014_S_0519',
 '014_S_0520',
 '014_S_0548',
 '014_S_0557',
 '014_S_0558',
 '014_S_0563',
 '016_S_0354',
 '016_S_0538',
 '016_S_0702',
 '016_S_0769',
 '016_S_0991',
 '016_S_1028',
 '016_S_1092',
 '016_S_1117',
 '016_S_1121',
 '016_S_1263',
 '016_S_1326',
 '018_S_0055',
 '018_S_0155',
 '018_S_0369',
 '020_S_0097',
 '020_S_0899',
 '020_S_1288',
 '021_S_0753',
 '022_S_0004',
 '022_S_0007',
 '022_S_0044',
 '022_S_0066',
 '022_S_0096',
 '022_S_0130',
 '022_S_0544',
 '022_S_0924',
 '022_S_0961',
 '022_S_1351',
 '022_S_1394',
 '023_S_0030',
 '023_S_0031',
 '023_S_0042',
 '023_S_0058',
 '023_S_0061',
 '023_S_0078',
 '023_S_0081',
 '023_S_0083',
 '023_S_0084',
 '023_S_0093',
 '023_S_0126',
 '023_S_0139',
 '023_S_0217',
 '023_S_0331',
 '023_S_0376',
 '023_S_0388',
 '023_S_0604',
 '023_S_0613',
 '023_S_0625',
 '023_S_0855',
 '023_S_0887',
 '023_S_0916',
 '023_S_0926',
 '023_S_0963',
 '023_S_1046',
 '023_S_1104',
 '023_S_1126',
 '023_S_1190',
 '023_S_1247',
 '023_S_1262',
 '024_S_0985',
 '024_S_1063',
 '024_S_1393',
 '027_S_0074',
 '027_S_0116',
 '027_S_0118',
 '027_S_0179',
 '027_S_0256',
 '027_S_0307',
 '027_S_0403',
 '027_S_0404',
 '027_S_0408',
 '027_S_0417',
 '027_S_0461',
 '027_S_0835',
 '027_S_1081',
 '027_S_1082',
 '027_S_1213',
 '027_S_1254',
 '027_S_1277',
 '027_S_1385',
 '027_S_1387',
 '029_S_0843',
 '029_S_0845',
 '029_S_0866',
 '029_S_0878',
 '029_S_0914',
 '029_S_1056',
 '029_S_1073',
 '029_S_1215',
 '029_S_1218',
 '029_S_1318',
 '029_S_1384',
 '031_S_0568',
 '031_S_1066',
 '031_S_1209',
 '032_S_0187',
 '032_S_0479',
 '032_S_0677',
 '033_S_0511',
 '033_S_0514',
 '033_S_0516',
 '033_S_0567',
 '033_S_0723',
 '033_S_0733',
 '033_S_0734',
 '033_S_0739',
 '033_S_0741',
 '033_S_0889',
 '033_S_0906',
 '033_S_0920',
 '033_S_0923',
 '033_S_1016',
 '033_S_1098',
 '033_S_1281',
 '033_S_1285',
 '033_S_1308',
 '035_S_0033',
 '035_S_0048',
 '035_S_0156',
 '035_S_0292',
 '035_S_0341',
 '035_S_0555',
 '035_S_0997',
 '036_S_0576',
 '036_S_0577',
 '036_S_0656',
 '036_S_0673',
 '036_S_0748',
 '036_S_0759',
 '036_S_0813',
 '036_S_0869',
 '036_S_0945',
 '036_S_1001',
 '036_S_1023',
 '036_S_1135',
 '036_S_1240',
 '037_S_0501',
 '037_S_0588',
 '037_S_1225',
 '041_S_0282',
 '041_S_0314',
 '041_S_0407',
 '041_S_0446',
 '041_S_0549',
 '041_S_0598',
 '041_S_0679',
 '041_S_1002',
 '041_S_1368',
 '041_S_1412',
 '041_S_1423',
 '041_S_1425',
 '051_S_1040',
 '051_S_1072',
 '051_S_1123',
 '051_S_1131',
 '051_S_1296',
 '051_S_1331',
 '051_S_1338',
 '052_S_0671',
 '052_S_0951',
 '052_S_0989',
 '052_S_1250',
 '052_S_1346',
 '052_S_1352',
 '053_S_0389',
 '053_S_0507',
 '053_S_0621',
 '053_S_0919',
 '053_S_1044',
 '057_S_0464',
 '057_S_0474',
 '057_S_0643',
 '057_S_0779',
 '057_S_0818',
 '057_S_0839',
 '057_S_0934',
 '057_S_0941',
 '057_S_0957',
 '057_S_1007',
 '057_S_1217',
 '057_S_1265',
 '057_S_1269',
 '057_S_1371',
 '057_S_1379',
 '062_S_0535',
 '062_S_0730',
 '062_S_0793',
 '062_S_1182',
 '062_S_1294',
 '062_S_1299',
 '067_S_0019',
 '067_S_0056',
 '067_S_0059',
 '067_S_0076',
 '067_S_0077',
 '067_S_0110',
 '067_S_0257',
 '067_S_0290',
 '067_S_0336',
 '067_S_0607',
 '067_S_0812',
 '067_S_1185',
 '067_S_1253',
 '073_S_0089',
 '073_S_0311',
 '073_S_0312',
 '073_S_0386',
 '073_S_0565',
 '073_S_0909',
 '073_S_1357',
 '082_S_0304',
 '082_S_0363',
 '082_S_0641',
 '082_S_0928',
 '082_S_1079',
 '082_S_1119',
 '082_S_1256',
 '094_S_0434',
 '094_S_0526',
 '094_S_0692',
 '094_S_0711',
 '094_S_0921',
 '094_S_1090',
 '094_S_1102',
 '094_S_1188',
 '094_S_1241',
 '094_S_1267',
 '094_S_1314',
 '094_S_1417',
 '098_S_0149',
 '098_S_0160',
 '098_S_0171',
 '098_S_0269',
 '098_S_0288',
 '098_S_0667',
 '098_S_0896',
 '099_S_0040',
 '099_S_0051',
 '099_S_0060',
 '099_S_0090',
 '099_S_0111',
 '099_S_0291',
 '099_S_0352',
 '099_S_0372',
 '099_S_0470',
 '099_S_0533',
 '099_S_0534',
 '099_S_0551',
 '099_S_0880',
 '099_S_0958',
 '099_S_1034',
 '099_S_1144',
 '109_S_0950',
 '109_S_0967',
 '109_S_1013',
 '109_S_1014',
 '109_S_1183',
 '109_S_1192',
 '109_S_1343',
 '114_S_0166',
 '114_S_0173',
 '114_S_0378',
 '114_S_0416',
 '114_S_0458',
 '114_S_0601',
 '114_S_0979',
 '114_S_1103',
 '114_S_1106',
 '116_S_0392',
 '116_S_0487',
 '116_S_0649',
 '116_S_0752',
 '116_S_1232',
 '116_S_1249',
 '126_S_0405',
 '126_S_0605',
 '126_S_0606',
 '126_S_0680',
 '126_S_0708',
 '126_S_0865',
 '126_S_1077',
 '126_S_1221',
 '126_S_1340',
 '127_S_0112',
 '127_S_0259',
 '127_S_0260',
 '127_S_0393',
 '127_S_0394',
 '127_S_0622',
 '127_S_0684',
 '127_S_0754',
 '127_S_0844',
 '127_S_0925',
 '127_S_1032',
 '127_S_1140',
 '127_S_1382',
 '127_S_1419',
 '127_S_1427',
 '128_S_0135',
 '128_S_0138',
 '128_S_0167',
 '128_S_0188',
 '128_S_0205',
 '128_S_0225',
 '128_S_0227',
 '128_S_0229',
 '128_S_0230',
 '128_S_0245',
 '128_S_0258',
 '128_S_0272',
 '128_S_0522',
 '128_S_0528',
 '128_S_0545',
 '128_S_0608',
 '128_S_0770',
 '128_S_0947',
 '128_S_1043',
 '128_S_1088',
 '128_S_1242',
 '128_S_1407',
 '128_S_1408',
 '130_S_0102',
 '130_S_0232',
 '130_S_0285',
 '130_S_0289',
 '130_S_0449',
 '130_S_0505',
 '130_S_0783',
 '130_S_1200',
 '130_S_1337',
 '131_S_0123',
 '131_S_0319',
 '131_S_0384',
 '131_S_0409',
 '131_S_0441',
 '131_S_0457',
 '131_S_0497',
 '131_S_0691',
 '131_S_1301',
 '131_S_1389',
 '133_S_0433',
 '133_S_0488',
 '133_S_0493',
 '133_S_0525',
 '133_S_0629',
 '133_S_0638',
 '133_S_0727',
 '133_S_0912',
 '133_S_0913',
 '133_S_1031',
 '133_S_1170',
 '136_S_0107',
 '136_S_0184',
 '136_S_0186',
 '136_S_0194',
 '136_S_0195',
 '136_S_0196',
 '136_S_0299',
 '136_S_0300',
 '136_S_0429',
 '136_S_0579',
 '136_S_0695',
 '136_S_0874',
 '136_S_1227',
 '141_S_0697',
 '141_S_0717',
 '141_S_0767',
 '141_S_0810',
 '141_S_0851',
 '141_S_0852',
 '141_S_0853',
 '141_S_0915',
 '141_S_0982',
 '141_S_1004',
 '141_S_1052',
 '141_S_1094',
 '141_S_1152',
 '141_S_1245',
 '141_S_1255',
 '941_S_1194',
 '941_S_1197',
 '941_S_1202',
 '941_S_1203',
 '941_S_1311'}

In [10]:
len(id_set)

456