In [1]:
import pandas as pd
import os

stat = pd.read_csv("FASTSURFER_MASKS/status_fastsurf.txt", header=None, names=['subj', 'status'], sep=":")

In [2]:
stat.head()

,subj,status
0,ADNI_035_S_0341_MR_MPR-R__GradWarp__B1_Correct...,Finished --seg_only successfully
1,ADNI_099_S_0551_MR_MPR-R__GradWarp__B1_Correct...,Finished --seg_only successfully
2,ADNI_013_S_0325_MR_MPR-R__GradWarp__B1_Correct...,Finished --seg_only successfully
3,ADNI_011_S_1282_MR_MPR-R__GradWarp__B1_Correct...,Finished --seg_only successfully
4,ADNI_094_S_1102_MR_MPR-R__GradWarp__B1_Correct...,Finished --seg_only successfully

In [3]:
subj = pd.read_csv('subjects.txt', header=None, names=['subj', 'path'], sep="=")

In [5]:
stat['subj'].nunique(), subj['subj'].nunique()

(145, 756)

In [6]:
stat['status'].value_counts()

status
Finished --seg_only successfully    145
Name: count, dtype: int64

In [87]:
stat[stat['status'] == ' Failed --seg_only with exit code 1']

,subj,status
4,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
5,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
712,ADNI_033_S_0516_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
820,ADNI_057_S_1379_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
973,ADNI_057_S_0464_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
...,...,...
1225,ADNI_035_S_0048_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1226,ADNI_057_S_1379_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1227,ADNI_094_S_1417_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1228,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1229,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1

In [88]:
stat.nunique()

subj      383
status      2
dtype: int64

In [89]:
stat.drop_duplicates(subset=['subj'], keep='first', inplace=True)

In [90]:
stat['status'].value_counts()

status
Finished --seg_only successfully      300
Failed --seg_only with exit code 1     83
Name: count, dtype: int64

In [7]:
stat[stat['status'] == ' Failed --seg_only with exit code 1']

Empty DataFrame
Columns: [subj, status]
Index: []

In [92]:
stat['subj'].nunique(), subj['subj'].nunique()

(383, 756)

In [93]:
stat[stat['status'] == ' Failed --seg_only with exit code 1'].drop_duplicates(subset=['subj'], keep='first', inplace=False)

,subj,status
4,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
5,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
712,ADNI_033_S_0516_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
820,ADNI_057_S_1379_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1018,AADNI_082_S_0641_MR_MPR-R__GradWarp__B1_Correc...,Failed --seg_only with exit code 1
...,...,...
1217,ADNI_027_S_0118_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1218,ADNI_023_S_0613_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1219,ADNI_002_S_1268_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1220,ADNI_941_S_1197_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1221,ADNI_057_S_1217_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1

In [94]:
stat[stat['status'] == ' Failed --seg_only with exit code 1']

,subj,status
4,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
5,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
712,ADNI_033_S_0516_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
820,ADNI_057_S_1379_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1018,AADNI_082_S_0641_MR_MPR-R__GradWarp__B1_Correc...,Failed --seg_only with exit code 1
...,...,...
1217,ADNI_027_S_0118_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1218,ADNI_023_S_0613_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1219,ADNI_002_S_1268_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1220,ADNI_941_S_1197_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1
1221,ADNI_057_S_1217_MR_MPR-R__GradWarp__B1_Correct...,Failed --seg_only with exit code 1

In [98]:
stat.drop(index=1018, inplace=True)

In [100]:
stat['path'] = '/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/' + stat['subj'] + '.nii'

In [101]:
stat[stat['status'] == ' Failed --seg_only with exit code 1'][['subj', 'path']].to_csv("to_process_fastsurf.txt", sep="=", index=False, header=False)

In [13]:
# process those not in stat but in subj
stat_subjs = stat['subj'].unique()
subj_subjs = subj['subj'].unique()
to_process = list(set(subj_subjs) - set(os.listdir('/home/e.yavarova/alzheimers_research_lala_emiliya/FASTSURFER_MASKS/')))
to_process_paths = subj[subj['subj'].isin(to_process)]
to_process_paths.to_csv("to_process_fastsurf_additional.txt", sep="=", index=False, header=False)

In [14]:
os.listdir('/home/e.yavarova/alzheimers_research_lala_emiliya/FASTSURFER_MASKS/')

['ADNI_036_S_0813_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071031134034806_S40099_I79925',
 'ADNI_136_S_0579_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080223194059268_S44768_I92092',
 'ADNI_027_S_1081_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071028195713680_S38366_I79200',
 'ADNI_041_S_0598_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071031141847950_S39217_I79977',
 'ADNI_031_S_0568_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080626141200113_S51249_I111227',
 'ADNI_033_S_0920_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070304121025723_S19288_I42481',
 'ADNI_057_S_0643_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071125144034849_S25943_I83130',
 'ADNI_013_S_0502_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070926112319750_S27532_I75295',
 'ADNI_011_S_0016_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061208144225208_S9254_I32318',
 'ADNI_029_S_1318_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071029185652390_S41201_I79599',
 'ADNI_033_S_1016_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090115183519769_S60925_I133906',
 'ADNI_033_S_1281_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070517161803030_S26136_I54780',
 'ADNI_041_S_1425_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070917110609443_S36929_I73361',
 'ADNI_128_S_0770_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070821194728009_S25985_I69719',
 'ADNI_133_S_0493_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070425175202891_S24042_I51028',
 'ADNI_032_S_0479_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080613154037775_S50883_I109528',
 'ADNI_027_S_0403_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061222191351273_S13717_I34181',
 'ADNI_099_S_0958_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061228154542455_S20493_I34594',
 'ADNI_133_S_0525_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070213223801999_S14992_I39984',
 'ADNI_031_S_1209_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071002184608174_S36417_I76662',
 'ADNI_029_S_1056_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080224133253927_S45642_I92182',
 'ADNI_941_S_1311_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081026142433381_S56646_I123816',
 'ADNI_027_S_1277_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080229160931558_S45863_I94462',
 'ADNI_099_S_0291_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080409164948743_S47067_I101786',
 'ADNI_033_S_0733_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070921083643279_S37300_I73993',
 'ADNI_014_S_0558_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070904191011045_S35310_I71433',
 'ADNI_057_S_1379_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20090514103130382_S66419_I143815',
 'ADNI_036_S_0869_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080125111443364_S31883_I88535',
 'ADNI_023_S_0030_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081001140030344_S20024_I118795',
 'ADNI_941_S_1194_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070801195835482_S25322_I63851',
 'ADNI_051_S_1072_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101109124614475_S81261_I203792',
 'ADNI_094_S_0921_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100108114348885_S75003_I162823',
 'ADNI_133_S_1170_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080207175003813_S24673_I89974',
 'ADNI_027_S_0408_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101111105300086_S85295_I204764',
 'ADNI_057_S_0934_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081104084856011_S57841_I125130',
 'ADNI_027_S_0307_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071226121155421_S20691_I86178',
 'ADNI_094_S_1241_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070808190503908_S26633_I66073',
 'ADNI_029_S_1215_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081017101050030_S55455_I121807',
 'ADNI_033_S_0723_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080307183043949_S45961_I96123',
 'ADNI_003_S_1074_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080221161737185_S45439_I91408',
 'ADNI_005_S_0602_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061212144916449_S17240_I32800',
 'ADNI_023_S_0031_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071229181610639_S42737_I86363',
 'ADNI_130_S_0783_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070807122315595_S28138_I65502',
 'ADNI_127_S_1032_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080626145345200_S51394_I111300',
 'ADNI_005_S_0448_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070904174304261_S32788_I71306',
 'ADNI_023_S_0061_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20090127163851356_S61044_I134693',
 'ADNI_099_S_0551_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080603174653463_S50494_I108241',
 'ADNI_022_S_0961_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20100106085230491_S76328_I162260',
 'ADNI_941_S_1202_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070801201337815_S25680_I63874',
 'ADNI_020_S_1288_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101102165135735_S81081_I201553',
 'ADNI_057_S_0818_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081027141443771_S56806_I124142',
 'ADNI_024_S_1063_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081204153701968_S58977_I129299',
 'ADNI_033_S_0516_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070809191253080_S33421_I66560',
 'ADNI_027_S_0074_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061222172044442_S16322_I34109',
 'ADNI_127_S_0622_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100108161032328_S69355_I162942',
 'ADNI_128_S_1088_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070819184202735_S23787_I69104',
 'ADNI_035_S_0292_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100112100221440_S68126_I163140',
 'ADNI_033_S_1285_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081026131803427_S56092_I123735',
 'ADNI_127_S_1427_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080220144535548_S37934_I91130',
 'ADNI_005_S_1224_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070923125912785_S37372_I74622',
 'ADNI_099_S_0372_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070418084733384_S22214_I49538',
 'ADNI_029_S_1384_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070805145632687_S29083_I64907',
 'ADNI_022_S_0130_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080229154208467_S45581_I94418',
 'ADNI_094_S_1314_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101110152111154_S81494_I204326',
 'ADNI_014_S_0356_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070320180425864_S20676_I45735',
 'ADNI_141_S_0767_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081022121223841_S27492_I122712',
 'ADNI_027_S_0116_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070920171535524_S36868_I73932',
 'ADNI_041_S_0314_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101109120253155_S85270_I203737',
 'ADNI_027_S_0256_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070808171933076_S29476_I66003',
 'ADNI_067_S_0336_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071221161459868_S32534_I85990',
 'ADNI_006_S_0731_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071027123708871_S38846_I78731',
 'ADNI_094_S_1417_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070918133138011_S35042_I73651',
 'ADNI_099_S_0090_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080414114559934_S26174_I102436',
 'ADNI_127_S_0754_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071104122600676_S18516_I80764',
 'ADNI_094_S_0711_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081023160731928_S55480_I123257',
 'ADNI_005_S_0602_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070921133908356_S37062_I74188',
 'ADNI_082_S_1079_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080318141316082_S46360_I98824',
 'ADNI_036_S_0656_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081023125754211_S54192_I123087',
 'ADNI_023_S_0613_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061203130106382_S15744_I31477',
 'ADNI_073_S_0565_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070828134943707_S26999_I70798',
 'ADNI_013_S_1205_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070426174047773_S25023_I51546',
 'ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20100601172719474_S78802_I176204',
 'ADNI_141_S_0697_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080220165125448_S18466_I91234',
 'ADNI_057_S_0643_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100111144202874_S70433_I163004',
 'ADNI_052_S_0951_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081204173549591_S58864_I129344',
 'ADNI_016_S_1326_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080421170033212_S47633_I103317',
 'ADNI_033_S_0889_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081029164228685_S57311_I124485',
 'ADNI_029_S_0866_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100111154031904_S75771_I163053',
 'ADNI_133_S_0629_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070219171507406_S15915_I40953',
 'ADNI_141_S_1152_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071029115237222_S36919_I79414',
 'ADNI_024_S_1063_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070731170617965_S21525_I63392',
 'ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080430143333279_S49114_I104356',
 'ADNI_057_S_0464_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20091203185321668_S69136_I160244',
 'ADNI_126_S_0405_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070209175521333_S15644_I38807',
 'ADNI_013_S_0996_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080113115738249_S31590_I87226',
 'ADNI_029_S_0866_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081103161736382_S57599_I125015',
 'ADNI_014_S_0563_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081022162716045_S54761_I122831',
 'ADNI_002_S_1155_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100426140642235_S78070_I171816',
 'ADNI_130_S_0289_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070801174842453_S28723_I63720',
 'ADNI_023_S_0042_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080111111455658_S43243_I87035',
 'ADNI_041_S_0446_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070806155716141_S24824_I65167',
 'ADNI_036_S_1023_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070806143820211_S24338_I65104',
 'ADNI_011_S_0023_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070808160000749_S23153_I65897',
 'ADNI_094_S_0526_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070731182838774_S14559_I63467',
 'ADNI_027_S_0461_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070807082804887_S34047_I65319',
 'ADNI_035_S_0997_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070730181050317_S23359_I62912',
 'ADNI_006_S_1130_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101118104104823_S78350_I205574',
 'ADNI_073_S_1357_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070731113515115_S29545_I63138',
 'ADNI_114_S_0173_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090717154627185_S64287_I149645',
 'ADNI_005_S_1224_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080430162944735_S49188_I104396',
 'ADNI_051_S_1331_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081016160027788_S42221_I121417',
 'ADNI_023_S_0061_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071113173035461_S23480_I81878',
 'ADNI_007_S_0344_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070118032630969_S12632_I36583',
 'ADNI_007_S_1206_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100601175816166_S80029_I176243',
 'ADNI_126_S_0708_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070912184458035_S36304_I72886',
 'ADNI_014_S_0520_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071027104917241_S24363_I78613',
 'ADNI_098_S_0667_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080229182000007_S44891_I94610',
 'ADNI_067_S_0019_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070319180821043_S9538_I45235',
 'ADNI_014_S_0356_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070212234215832_S12856_I39633',
 'ADNI_053_S_0389_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070809203722621_S22123_I66639',
 'ADNI_128_S_0138_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070818150340120_S18460_I68643',
 'ADNI_130_S_0102_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070212204139243_S10747_I39463',
 'ADNI_029_S_0845_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100106123220520_S75198_I162418',
 'ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061212171807772_S12599_I32892',
 'ADNI_033_S_0741_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080302104153083_S26615_I94812',
 'ADNI_128_S_0229_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080410164245717_S47907_I102221',
 'ADNI_041_S_0446_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070215230040560_S13908_I40433',
 'ADNI_099_S_0551_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080225181435042_S43126_I92572',
 'ADNI_033_S_0511_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070302153643881_S23684_I42253',
 'ADNI_023_S_0926_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070805135409771_S29261_I64844',
 'ADNI_073_S_0089_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081006105102890_S11161_I119227',
 'ADNI_011_S_1282_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090511130724223_S63672_I143505',
 'ADNI_062_S_1299_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081020083820861_S56467_I122154',
 'ADNI_023_S_0625_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081013171424457_S54690_I120455',
 'ADNI_109_S_1014_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081110163401898_S58146_I125924',
 'ADNI_036_S_1240_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20090420151815490_S63956_I142021',
 'ADNI_098_S_0896_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081125161838202_S58297_I128551',
 'ADNI_141_S_1094_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070402175947403_S23295_I47736',
 'ADNI_057_S_0934_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070730184824897_S30605_I62964',
 'ADNI_094_S_1267_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20091202160245913_S69242_I160050',
 'ADNI_941_S_1197_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070809164507041_S25331_I66466',
 'ADNI_002_S_0954_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080107130435931_S41499_I86638',
 'ADNI_023_S_0376_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080116082909377_S41959_I87511',
 'ADNI_005_S_0448_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080611155649175_S50866_I109182',
 'ADNI_023_S_0139_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080318134254807_S46599_I98780',
 'ADNI_051_S_1131_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080223163909066_S45358_I91837',
 'ADNI_033_S_1016_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20110222130319826_S94540_I218770',
 'ADNI_062_S_0793_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070424124729305_S27206_I50537',
 'ADNI_116_S_0752_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080220142120973_S42375_I91084',
 'ADNI_014_S_0520_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081024160951274_S52565_I123639',
 'ADNI_022_S_0007_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070804135719844_S13797_I64648',
 'ADNI_027_S_0074_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070327125605917_S24557_I47075',
 'ADNI_082_S_0363_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070213172657494_S13016_I39733',
 'ADNI_023_S_1247_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070427204448475_S26860_I52142',
 'ADNI_029_S_0878_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080220101735923_S42146_I90893',
 'ADNI_051_S_1131_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071101164927229_S36811_I80174',
 'ADNI_005_S_0610_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070923122713025_S37098_I74586',
 'ADNI_094_S_0692_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081208170003641_S58718_I129580',
 'ADNI_027_S_0835_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070109233940992_S18760_I35665',
 'ADNI_041_S_1423_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081017080256795_S55787_I121665',
 'ADNI_116_S_0392_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080206163640894_S23632_I89657',
 'ADNI_099_S_0111_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070110235309190_S10934_I35852',
 'ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090723163637429_S68160_I150223',
 'ADNI_023_S_0331_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100601182419728_S84477_I176278',
 'ADNI_002_S_1268_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070802165652566_S26499_I64041',
 'ADNI_141_S_1255_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070411124958080_S25886_I48612',
 'ADNI_094_S_1188_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070913163914979_S35159_I73177',
 'ADNI_057_S_1371_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071101175535150_S40935_I80252',
 'ADNI_098_S_0269_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070812145531201_S29779_I67236',
 'ADNI_023_S_0963_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070806122430634_S29233_I65008',
 'ADNI_035_S_0156_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070212215232849_S11392_I39537',
 'ADNI_126_S_0605_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070209184426626_S15666_I38863',
 'ADNI_023_S_0331_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090717141549915_S66020_I149521',
 'ADNI_023_S_0078_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081001153036948_S10619_I118861',
 'ADNI_023_S_0058_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061128092535270_S10334_I30554',
 'ADNI_041_S_0549_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080313111328817_S46692_I97120',
 'ADNI_127_S_0393_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080123094105781_S43806_I88108',
 'ADNI_116_S_0487_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080225095154223_S33715_I92424',
 'ADNI_027_S_1082_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070807091757105_S33128_I65369',
 'ADNI_051_S_1072_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070807164502749_S25625_I65661',
 'ADNI_136_S_0184_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080415155407206_S48056_I102849',
 'ADNI_023_S_0084_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070427193110994_S25511_I52043',
 'ADNI_013_S_0325_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070517130305186_S13523_I54668',
 'ADNI_126_S_1221_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070412185035131_S25456_I48971',
 'ADNI_098_S_0171_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100429100745114_S80351_I172315',
 'ADNI_031_S_1066_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080225191153235_S32777_I92682',
 'ADNI_114_S_1106_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070821152743442_S33277_I69505',
 'ADNI_126_S_1077_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100301135035645_S77220_I167034',
 'ADNI_005_S_0546_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070818113852943_S25839_I68423',
 'ADNI_022_S_0924_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070712160908877_S19446_I59579',
 'ADNI_007_S_0128_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070713104335049_S26557_I59869',
 'ADNI_053_S_0507_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090730115525280_S67537_I151131',
 'ADNI_057_S_0474_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061229153747701_S13990_I34720',
 'ADNI_023_S_0217_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061201161418019_S17864_I31354',
 'ADNI_002_S_0413_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070319120107557_S13894_I45121',
 'ADNI_099_S_0291_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071101200621586_S41015_I80446',
 'ADNI_082_S_0641_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070213182825664_S15700_I39784',
 'ADNI_053_S_1044_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070802192047518_S21256_I64202',
 'ADNI_016_S_0538_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100114160940971_S55407_I163713',
 'ADNI_027_S_0835_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081023104917407_S56476_I122967',
 'ADNI_022_S_1351_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070927172211201_S39001_I75646',
 'ADNI_024_S_1393_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071029182926249_S41562_I79563',
 'ADNI_126_S_0680_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070412182036876_S25498_I48936',
 'ADNI_128_S_1043_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070820164905443_S34308_I69281',
 'ADNI_027_S_1254_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090316154022446_S63692_I139078',
 'ADNI_062_S_0730_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070424120901998_S17061_I50491',
 'ADNI_033_S_1098_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070306095209723_S22792_I42831',
 'ADNI_136_S_0695_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070911132443199_S29253_I72586',
 'ADNI_130_S_0449_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071106110616360_S22250_I80930',
 'ADNI_022_S_0544_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080522114908716_S50132_I106462',

In [ ]:
ADNI_023_S_0604_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080123084337542_S43616_I88044: Failed --seg_only with exit code 1

In [12]:
import os
import pandas as pd
dirs = sorted(os.listdir('/home/e.yavarova/alzheimers_research_lala_emiliya/FASTSURFER_MASKS/'))
subj = pd.read_csv('subjects.txt', header=None, names=['subj', 'path'], sep="=")
subj_subjs = sorted(subj['subj'])
subj_subjs == dirs

False

In [15]:
import pandas as pd

In [18]:
missing = pd.read_csv('missing_fastsurfer_masks.csv')
missing['path'] = missing['id'] + '=/home/e.yavarova/alzheimers_research_lala_emiliya/MRIs_IMAGES_FILTERED_NOMASKS/' + missing['id'] + '.nii'

In [21]:
missing['path'].to_csv('to_process_fastsurf_missing_masks.txt', index=False, header=False)